# Generated by Django 3.0.6 on 2020-05-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_article_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='genre',
        ),
    ]
